import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  MessageSquare,
  Clock,
  Trash2,
  Play,
  Search,
  FileDown,
  Bot,
  User,
  X,
  CheckSquare,
  Square,
  ChevronRight,
  ShieldAlert,
  AlertCircle,
  Calendar,
  Hash,
  Inbox,
  Filter,
  RotateCcw,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { getSessions, deleteSession } from '../utils/chatHistoryStore';
import { ChatSession, ChatMessage } from '../types/chat';

// ─────────────────────────────────────────────────────────────────────────────
// PDF export — pure browser, no external dependency required
// Uses jsPDF loaded dynamically to keep bundle lean
// ─────────────────────────────────────────────────────────────────────────────
async function exportSessionToPDF(session: ChatSession): Promise<void> {
  // Dynamic import so it only loads when needed
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addPageIfNeeded = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
      drawPageHeader();
    }
  };

  const drawPageHeader = () => {
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageW, 12, 'F');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text('KSP SHERLOCK — CONFIDENTIAL INVESTIGATION TRANSCRIPT', margin, 8);
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageW - margin, 8, { align: 'right' });
  };

  // ── Cover block ──
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageW, pageH, 'F');

  // Header stripe
  doc.setFillColor(0, 212, 170);
  doc.rect(0, 0, 6, pageH, 'F');

  // Title
  doc.setFontSize(22);
  doc.setTextColor(0, 212, 170);
  doc.setFont('helvetica', 'bold');
  doc.text('SHERLOCK', margin + 6, 38);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.setFont('helvetica', 'normal');
  doc.text('KSP AI Crime Investigation Assistant', margin + 6, 46);

  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.4);
  doc.line(margin + 6, 52, pageW - margin, 52);

  doc.setFontSize(13);
  doc.setTextColor(226, 232, 240);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(`"${session.title}"`, contentW - 10);
  doc.text(titleLines, margin + 6, 62);

  y = 62 + titleLines.length * 7 + 6;

  // Meta table
  const metas = [
    ['Session ID', session.id],
    ['Date', session.timestamp],
    ['Total Messages', String(session.messages.length)],
    ['User Messages', String(session.messages.filter(m => m.sender === 'user').length)],
    ['AI Responses', String(session.messages.filter(m => m.sender === 'ai').length)],
    ['Export Time', new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })],
  ];

  metas.forEach(([label, value]) => {
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text(label + ':', margin + 6, y);
    doc.setTextColor(203, 213, 225);
    doc.text(value, margin + 55, y);
    y += 6;
  });

  y += 4;
  doc.setDrawColor(30, 41, 59);
  doc.line(margin + 6, y, pageW - margin, y);
  y += 8;

  // Audit badge
  doc.setFillColor(0, 212, 170, 0.08);
  doc.roundedRect(margin + 6, y, contentW - 6, 10, 2, 2, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(0, 212, 170);
  doc.setFont('helvetica', 'bold');
  doc.text('⚑  LOGGED AUDIT TRAIL — GENERATED BY KSP SHERLOCK NEURAL ENGINE', margin + 10, y + 6.5);
  y += 18;

  // ── Transcript pages ──
  doc.addPage();
  y = margin;
  drawPageHeader();
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(0, 212, 170);
  doc.setFont('helvetica', 'bold');
  doc.text('CONVERSATION TRANSCRIPT', margin, y);
  y += 8;

  session.messages.forEach((msg, idx) => {
    const isUser = msg.sender === 'user';

    addPageIfNeeded(18);

    // Sender label row
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(isUser ? 56 : 0, isUser ? 189 : 212, isUser ? 248 : 170);
    doc.text(isUser ? `[OFFICER]  ${msg.timestamp}` : `[SHERLOCK]  ${msg.timestamp}`, margin, y);
    y += 4;

    // Message bubble background
    const textLines = doc.splitTextToSize(msg.text, contentW - 8);
    const bubbleH = textLines.length * 4.5 + 6;

    addPageIfNeeded(bubbleH + 4);

    if (isUser) {
      doc.setFillColor(14, 40, 70);
    } else if (msg.isError) {
      doc.setFillColor(60, 10, 10);
    } else {
      doc.setFillColor(15, 23, 42);
    }
    doc.roundedRect(margin, y, contentW, bubbleH, 2, 2, 'F');

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(msg.isError ? 248 : 203, msg.isError ? 113 : 213, msg.isError ? 113 : 225);
    doc.text(textLines, margin + 4, y + 5);
    y += bubbleH + 6;

    // Divider every 5 messages
    if ((idx + 1) % 5 === 0) {
      addPageIfNeeded(6);
      doc.setDrawColor(30, 41, 59);
      doc.setLineWidth(0.2);
      doc.line(margin, y, pageW - margin, y);
      y += 4;
    }
  });

  // ── Footer ──
  addPageIfNeeded(20);
  y += 6;
  doc.setDrawColor(30, 41, 59);
  doc.line(margin, y, pageW - margin, y);
  y += 6;
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(
    'This document is generated by KSP SHERLOCK and is classified as a confidential law-enforcement record.',
    margin,
    y,
    { maxWidth: contentW }
  );
  y += 5;
  doc.text(
    'Unauthorised disclosure is a criminal offence under applicable laws.',
    margin,
    y
  );

  const safeTitle = session.title.replace(/[^a-z0-9]/gi, '_').substring(0, 40);
  doc.save(`KSP_SHERLOCK_${safeTitle}_${Date.now()}.pdf`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
function formatRelativeTime(raw: string): string {
  const d = new Date(raw);
  if (isNaN(d.getTime())) return raw;
  const diff = Date.now() - d.getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'Just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `${days}d ago`;
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function getSessionPreview(session: ChatSession): string {
  const lastAI = [...session.messages].reverse().find(m => m.sender === 'ai' && !m.isError);
  return lastAI ? lastAI.text.substring(0, 120) + (lastAI.text.length > 120 ? '...' : '') : 'No AI response yet.';
}

// ─────────────────────────────────────────────────────────────────────────────
// Session Detail Drawer
// ─────────────────────────────────────────────────────────────────────────────
function SessionDrawer({
  session,
  onClose,
  onResume,
  onExport,
  onDelete,
}: {
  session: ChatSession;
  onClose: () => void;
  onResume: () => void;
  onExport: () => void;
  onDelete: () => void;
}) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try { await onExport(); } finally { setExporting(false); }
  };

  return (
    <motion.div
      key="drawer"
      initial={{ x: '100%', opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      exit={{ x: '100%', opacity: 0 }}
      transition={{ type: 'spring', stiffness: 320, damping: 34 }}
      className="fixed inset-y-0 right-0 z-50 w-full max-w-md flex flex-col bg-abyss border-l border-edge/70 shadow-2xl"
    >
      {/* Drawer header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-edge/60 bg-panel/60 backdrop-blur-sm shrink-0">
        <div className="flex items-center gap-2">
          <MessageSquare className="h-4 w-4 text-neon-bright" />
          <span className="font-mono text-xs text-slate-400 uppercase tracking-widest">Session Detail</span>
        </div>
        <button onClick={onClose} className="text-slate-500 hover:text-slate-200 transition-colors">
          <X className="h-5 w-5" />
        </button>
      </div>

      {/* Session meta */}
      <div className="px-5 py-4 border-b border-edge/40 bg-panel/30 shrink-0">
        <h2 className="font-display font-bold text-slate-100 text-base leading-snug mb-2 line-clamp-2">
          "{session.title}"
        </h2>
        <div className="flex flex-wrap gap-3 text-[10px] font-mono text-slate-500">
          <span className="flex items-center gap-1">
            <Calendar className="h-3 w-3" /> {formatRelativeTime(session.timestamp)}
          </span>
          <span className="flex items-center gap-1">
            <Hash className="h-3 w-3" /> {session.messages.length} messages
          </span>
          <span className="flex items-center gap-1">
            <User className="h-3 w-3" /> {session.messages.filter(m => m.sender === 'user').length} from you
          </span>
          <span className="flex items-center gap-1">
            <Bot className="h-3 w-3" /> {session.messages.filter(m => m.sender === 'ai').length} from AI
          </span>
        </div>
      </div>

      {/* Message transcript */}
      <div className="flex-1 overflow-y-auto custom-scrollbar px-4 py-4 space-y-3">
        {session.messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex items-start gap-2 ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            {msg.sender === 'ai' && (
              <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-neon/10 border border-neon/20 text-neon-bright mt-0.5">
                <Bot className="h-3.5 w-3.5" />
              </div>
            )}
            <div className={`max-w-[85%] rounded-xl px-3 py-2 text-xs font-body leading-relaxed ${
              msg.sender === 'user'
                ? 'bg-neon/15 border border-neon/30 text-slate-100 rounded-tr-none'
                : msg.isError
                ? 'bg-red-500/10 border border-red-500/20 text-red-300 rounded-tl-none'
                : 'bg-panel border border-edge/60 text-slate-300 rounded-tl-none'
            }`}>
              {msg.isError && (
                <div className="flex items-center gap-1 mb-1 font-mono text-[9px] text-red-400">
                  <AlertCircle className="h-3 w-3" /> ERROR
                </div>
              )}
              <p className="whitespace-pre-wrap break-words">{msg.text}</p>
              <div className="flex items-center justify-end gap-1 mt-1 text-[9px] font-mono text-slate-600">
                <Clock className="h-2 w-2" /> {msg.timestamp}
              </div>
            </div>
            {msg.sender === 'user' && (
              <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-neon/10 border border-neon/20 text-neon-bright mt-0.5">
                <User className="h-3.5 w-3.5" />
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Action bar */}
      <div className="px-5 py-4 border-t border-edge/60 bg-panel/40 backdrop-blur-sm flex items-center gap-2 shrink-0">
        <button
          onClick={handleExport}
          disabled={exporting}
          className="flex-1 flex items-center justify-center gap-2 px-3 py-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/20 transition-all font-mono text-xs font-bold disabled:opacity-50"
        >
          <FileDown className="h-3.5 w-3.5" />
          {exporting ? 'Exporting...' : 'Export PDF'}
        </button>

        <button
          onClick={onResume}
          className="flex-1 flex items-center justify-center gap-2 px-3 py-2.5 rounded-lg bg-neon/10 border border-neon/30 text-neon-bright hover:bg-neon/20 transition-all font-mono text-xs font-bold"
        >
          <Play className="h-3.5 w-3.5" />
          Resume Chat
        </button>

        <button
          onClick={onDelete}
          className="flex items-center justify-center p-2.5 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 hover:bg-red-500/20 transition-all"
          title="Delete session"
        >
          <Trash2 className="h-4 w-4" />
        </button>
      </div>
    </motion.div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────────────────────────────────
type SortKey = 'recent' | 'oldest' | 'longest' | 'shortest';

export default function ConversationHistory() {
  const { currentUser } = useAuth();
  const navigate = useNavigate();

  const [sessions, setSessions] = useState<ChatSession[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [sortKey, setSortKey] = useState<SortKey>('recent');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [activeSession, setActiveSession] = useState<ChatSession | null>(null);
  const [exportingId, setExportingId] = useState<string | null>(null);
  const [showFilterMenu, setShowFilterMenu] = useState(false);

  useEffect(() => {
    if (currentUser?.uid) {
      setSessions(getSessions(currentUser.uid));
    }
  }, [currentUser]);

  // ── Filtering & sorting ──
  const filtered = sessions
    .filter(s => {
      const q = searchTerm.toLowerCase();
      if (!q) return true;
      return (
        s.title.toLowerCase().includes(q) ||
        s.messages.some(m => m.text.toLowerCase().includes(q))
      );
    })
    .sort((a, b) => {
      switch (sortKey) {
        case 'recent':  return new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime();
        case 'oldest':  return new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime();
        case 'longest': return b.messages.length - a.messages.length;
        case 'shortest':return a.messages.length - b.messages.length;
        default:        return 0;
      }
    });

  // ── Selection ──
  const toggleSelect = useCallback((e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    setSelectedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }, []);

  const selectAll = () => setSelectedIds(new Set(filtered.map(s => s.id)));
  const clearSelection = () => setSelectedIds(new Set());

  // ── Delete ──
  const handleDelete = (e: React.MouseEvent, sessionId: string) => {
    e.stopPropagation();
    if (!currentUser?.uid) return;
    deleteSession(currentUser.uid, sessionId);
    setSessions(prev => prev.filter(s => s.id !== sessionId));
    if (activeSession?.id === sessionId) setActiveSession(null);
    setSelectedIds(prev => { const n = new Set(prev); n.delete(sessionId); return n; });
  };

  const handleBulkDelete = () => {
    if (!currentUser?.uid || selectedIds.size === 0) return;
    selectedIds.forEach(id => deleteSession(currentUser.uid!, id));
    setSessions(prev => prev.filter(s => !selectedIds.has(s.id)));
    if (activeSession && selectedIds.has(activeSession.id)) setActiveSession(null);
    clearSelection();
  };

  // ── Resume ──
  const handleResume = (session: ChatSession) => {
    navigate('/dashboard/ai-assistant', { state: { session } });
  };

  // ── PDF export ──
  const handleExport = async (e: React.MouseEvent, session: ChatSession) => {
    e.stopPropagation();
    setExportingId(session.id);
    try { await exportSessionToPDF(session); } finally { setExportingId(null); }
  };

  const sortLabels: Record<SortKey, string> = {
    recent: 'Most Recent',
    oldest: 'Oldest First',
    longest: 'Most Messages',
    shortest: 'Fewest Messages',
  };

  return (
    <>
      {/* Backdrop for drawer */}
      <AnimatePresence>
        {activeSession && (
          <motion.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm"
            onClick={() => setActiveSession(null)}
          />
        )}
      </AnimatePresence>

      {/* Side drawer */}
      <AnimatePresence>
        {activeSession && (
          <SessionDrawer
            session={activeSession}
            onClose={() => setActiveSession(null)}
            onResume={() => handleResume(activeSession)}
            onExport={() => exportSessionToPDF(activeSession)}
            onDelete={() => {
              if (!currentUser?.uid) return;
              deleteSession(currentUser.uid, activeSession.id);
              setSessions(prev => prev.filter(s => s.id !== activeSession.id));
              setActiveSession(null);
            }}
          />
        )}
      </AnimatePresence>

      <div className="flex flex-col h-full max-w-7xl mx-auto space-y-5">

        {/* ── Header ── */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-edge/60 pb-4 shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-neon/10 border border-neon/30 text-neon-bright shadow-neon-sm">
              <MessageSquare className="h-6 w-6" />
            </div>
            <div>
              <h1 className="font-display text-2xl font-bold tracking-wide text-slate-100">
                Conversation History
              </h1>
              <p className="font-body text-xs text-slate-400 mt-0.5">
                Secure Archives · {sessions.length} session{sessions.length !== 1 ? 's' : ''} stored
              </p>
            </div>
          </div>

          {/* Search + Sort */}
          <div className="flex items-center gap-2 flex-wrap">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-500" />
              <input
                type="text"
                placeholder="Search transcripts..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
                className="pl-9 pr-4 py-2 rounded-lg bg-panel border border-edge text-xs text-slate-200 outline-none focus:border-neon focus:ring-1 focus:ring-neon transition-all w-52 font-body"
              />
              {searchTerm && (
                <button onClick={() => setSearchTerm('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300">
                  <X className="h-3.5 w-3.5" />
                </button>
              )}
            </div>

            {/* Sort dropdown */}
            <div className="relative">
              <button
                onClick={() => setShowFilterMenu(v => !v)}
                className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-panel border border-edge hover:border-neon/40 text-xs font-mono text-slate-300 transition-all"
              >
                <Filter className="h-3.5 w-3.5 text-slate-500" />
                {sortLabels[sortKey]}
                <ChevronRight className={`h-3 w-3 text-slate-500 transition-transform ${showFilterMenu ? 'rotate-90' : ''}`} />
              </button>
              <AnimatePresence>
                {showFilterMenu && (
                  <>
                    <div className="fixed inset-0 z-30" onClick={() => setShowFilterMenu(false)} />
                    <motion.div
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: 4 }}
                      className="absolute right-0 top-full mt-1.5 w-44 rounded-lg border border-edge bg-panel shadow-2xl z-40 overflow-hidden font-mono"
                    >
                      {(Object.keys(sortLabels) as SortKey[]).map(key => (
                        <button
                          key={key}
                          onClick={() => { setSortKey(key); setShowFilterMenu(false); }}
                          className={`w-full text-left px-4 py-2.5 text-xs transition-colors flex items-center justify-between ${
                            sortKey === key ? 'text-neon-bright bg-edge' : 'text-slate-300 hover:bg-edge hover:text-neon-bright'
                          }`}
                        >
                          {sortLabels[key]}
                          {sortKey === key && <span className="h-1.5 w-1.5 rounded-full bg-neon-bright" />}
                        </button>
                      ))}
                    </motion.div>
                  </>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>

        {/* ── Bulk action bar ── */}
        <AnimatePresence>
          {selectedIds.size > 0 && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="flex items-center justify-between px-4 py-2.5 rounded-xl bg-amber-500/10 border border-amber-500/30 shrink-0"
            >
              <div className="flex items-center gap-2">
                <CheckSquare className="h-4 w-4 text-amber-400" />
                <span className="font-mono text-xs text-amber-300 font-bold">
                  {selectedIds.size} session{selectedIds.size !== 1 ? 's' : ''} selected
                </span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={selectAll}
                  className="font-mono text-[10px] text-slate-400 hover:text-slate-200 transition-colors"
                >
                  Select All
                </button>
                <button
                  onClick={clearSelection}
                  className="font-mono text-[10px] text-slate-400 hover:text-slate-200 transition-colors"
                >
                  Clear
                </button>
                <button
                  onClick={handleBulkDelete}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-500/15 border border-red-500/30 text-red-400 hover:bg-red-500/25 transition-all font-mono text-xs font-bold"
                >
                  <Trash2 className="h-3.5 w-3.5" /> Delete Selected
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* ── Session grid ── */}
        <div className="flex-1 overflow-y-auto custom-scrollbar">
          {sessions.length === 0 ? (
            /* Empty state */
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex flex-col items-center justify-center min-h-[50vh] text-center"
            >
              <div className="relative mb-6">
                <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-void/50 border border-edge text-slate-600">
                  <Inbox className="h-10 w-10" />
                </div>
                <div className="absolute -bottom-1 -right-1 flex h-7 w-7 items-center justify-center rounded-lg bg-neon/10 border border-neon/30">
                  <MessageSquare className="h-4 w-4 text-neon-bright" />
                </div>
              </div>
              <h3 className="font-display text-lg font-bold tracking-wide text-slate-300">
                No Sessions Yet
              </h3>
              <p className="mt-2 font-body text-xs text-slate-500 max-w-sm leading-relaxed">
                Your AI investigation conversations will be securely archived here. Start a chat with SHERLOCK to build your history.
              </p>
              <button
                onClick={() => navigate('/dashboard/ai-assistant')}
                className="mt-6 flex items-center gap-2 px-4 py-2.5 rounded-xl bg-neon/10 border border-neon/30 text-neon-bright hover:bg-neon/20 transition-all font-mono text-xs font-bold"
              >
                <Play className="h-3.5 w-3.5" /> Start New Investigation
              </button>
            </motion.div>
          ) : filtered.length === 0 ? (
            /* No search results */
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center justify-center min-h-[30vh] text-center gap-3"
            >
              <Search className="h-8 w-8 text-slate-600" />
              <p className="font-mono text-sm text-slate-500">No sessions match <span className="text-slate-300">"{searchTerm}"</span></p>
              <button
                onClick={() => setSearchTerm('')}
                className="flex items-center gap-1.5 text-xs font-mono text-neon-bright hover:underline"
              >
                <RotateCcw className="h-3 w-3" /> Clear search
              </button>
            </motion.div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 pb-4">
              <AnimatePresence mode="popLayout">
                {filtered.map(session => {
                  const isSelected = selectedIds.has(session.id);
                  const isExporting = exportingId === session.id;

                  return (
                    <motion.div
                      key={session.id}
                      layout
                      initial={{ opacity: 0, scale: 0.96 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.96, transition: { duration: 0.15 } }}
                      className={`group relative rounded-xl border bg-panel/40 backdrop-blur-sm flex flex-col transition-all cursor-pointer overflow-hidden ${
                        isSelected
                          ? 'border-amber-500/50 bg-amber-500/5 shadow-[0_0_0_1px_rgba(245,158,11,0.15)]'
                          : 'border-edge hover:border-neon/40 hover:bg-panel/70 hover:shadow-lg'
                      }`}
                      onClick={() => setActiveSession(session)}
                    >
                      {/* Top accent bar */}
                      <div className={`h-0.5 w-full ${isSelected ? 'bg-amber-400' : 'bg-gradient-to-r from-neon/30 to-transparent group-hover:from-neon/60'} transition-all`} />

                      <div className="p-5 flex flex-col gap-3 flex-1">
                        {/* Title row */}
                        <div className="flex items-start gap-2">
                          <div
                            onClick={e => toggleSelect(e, session.id)}
                            className="mt-0.5 shrink-0 text-slate-600 hover:text-amber-400 transition-colors cursor-pointer"
                            title="Select"
                          >
                            {isSelected
                              ? <CheckSquare className="h-4 w-4 text-amber-400" />
                              : <Square className="h-4 w-4" />
                            }
                          </div>
                          <h3 className="font-display font-semibold text-slate-200 text-sm line-clamp-2 leading-snug flex-1 group-hover:text-neon-bright transition-colors">
                            "{session.title}"
                          </h3>
                        </div>

                        {/* Preview of last AI message */}
                        <p className="font-body text-[11px] text-slate-500 leading-relaxed line-clamp-2">
                          {getSessionPreview(session)}
                        </p>

                        {/* Meta pills */}
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="flex items-center gap-1 px-2 py-1 rounded-md bg-void/50 border border-edge/50 font-mono text-[9px] text-slate-500">
                            <Clock className="h-2.5 w-2.5" /> {formatRelativeTime(session.timestamp)}
                          </span>
                          <span className="flex items-center gap-1 px-2 py-1 rounded-md bg-void/50 border border-edge/50 font-mono text-[9px] text-slate-500">
                            <Hash className="h-2.5 w-2.5" /> {session.messages.length} msgs
                          </span>
                          {session.messages.some(m => m.isError) && (
                            <span className="flex items-center gap-1 px-2 py-1 rounded-md bg-red-500/10 border border-red-500/20 font-mono text-[9px] text-red-400">
                              <AlertCircle className="h-2.5 w-2.5" /> Errors
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Action footer */}
                      <div className="flex items-center justify-between border-t border-edge/40 px-4 py-2.5 bg-void/20">
                        <div className="flex items-center gap-1">
                          <button
                            onClick={e => handleDelete(e, session.id)}
                            className="p-1.5 rounded-md text-slate-600 hover:text-red-400 hover:bg-red-400/10 transition-colors"
                            title="Delete"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>

                          <button
                            onClick={e => handleExport(e, session)}
                            disabled={isExporting}
                            className="p-1.5 rounded-md text-slate-600 hover:text-emerald-400 hover:bg-emerald-400/10 transition-colors disabled:opacity-40"
                            title="Export PDF"
                          >
                            <FileDown className={`h-3.5 w-3.5 ${isExporting ? 'animate-bounce' : ''}`} />
                          </button>
                        </div>

                        <div className="flex items-center gap-2">
                          <span className="font-mono text-[9px] text-slate-600 flex items-center gap-1">
                            <ShieldAlert className="h-2.5 w-2.5" /> Audit logged
                          </span>
                          <div className="flex items-center gap-1 font-mono text-[10px] font-bold text-neon-bright bg-neon/10 border border-neon/20 px-2.5 py-1 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity">
                            <ChevronRight className="h-3 w-3" /> View
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </AnimatePresence>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
